### ISSUE TITLE
后台显示不正常

### ISSUE THREAD

**Issue by jason4677** [GaHoKwan/tvpanel#12]
系统页  Fatal error: Call to undefined function get_config() in D:\localuser\ftp6359396\Web\admin\sysadmin.php on line 393

EPG列表页   Fatal error: Call to undefined function get_config() in D:\localuser\ftp6359396\Web\admin\epgadmin.php on line 191

异常用户页

**Comment by GaHoKwan** [comment]
更新一下config.php
