### ISSUE TITLE
sysadmin.php 314行报错后台

### ISSUE THREAD

**Issue by shuaigebo** [GaHoKwan/tvpanel#2]
Warning: mysqli_fetch_array() expects parameter 1 to be mysqli_result, bool given in D:\wwwroot\kyepg\admin\sysadmin.php on line 314

**Comment by shuaigebo** [comment]
再补充一个 频道列表无法更改分类名称

**Comment by shuaigebo** [comment]
epgadmin.php里面两个跳转连接还是epg.php

**Comment by GaHoKwan** [comment]
刚刚在更新
