### ISSUE TITLE
sysadmin.php点击导出用户数据报错无法完成

### ISSUE THREAD

**Issue by shuaigebo** [GaHoKwan/tvpanel#4]
Warning: mysqli_query() expects parameter 1 to be mysqli, null given in D:\wwwroot\kyepg\admin\sysadmin.php on line 166

Warning: mysqli_fetch_array() expects parameter 1 to be mysqli_result, null given in D:\wwwroot\kyepg\admin\sysadmin.php on line 167

Warning: mysqli_free_result() expects parameter 1 to be mysqli_result, null given in D:\wwwroot\kyepg\admin\sysadmin.php on line 171

**Comment by GaHoKwan** [comment]
已修复[https://github.com/GaHoKwan/tvpanel/commit/c64b21a3491dbfc92afb803d616fbbed4805434f](https://github.com/GaHoKwan/tvpanel/commit/c64b21a3491dbfc92afb803d616fbbed4805434f)
