### ISSUE TITLE
昨晚升级后无法登陆提示升级失败

### ISSUE THREAD

**Issue by shuaigebo** [GaHoKwan/tvpanel#6]
无法自动授权登陆，手动创建账号，点2次后可以登陆，清空数据后无法登录提示升级失败

**Comment by shuaigebo** [comment]
active.php 42行$json=file_get_contents(dirname($myurl)."/getip.php?ip=$ip"); 应该改为
$json=file_get_contents(dirname($myurl)."/getIpInfo.php?ip=$ip");

**Comment by shuaigebo** [comment]
还有改了之后依然提示升级失败

**Comment by shuaigebo** [comment]
Warning: mysqli_fetch_array() expects parameter 1 to be mysqli_result, boolean given in D:\wwwroot\EPG\admin\sysadmin.php on line 341

Warning: mysqli_free_result() expects parameter 1 to be mysqli_result, boolean given in D:\wwwroot\EPG\admin\sysadmin.php on line 368

**Comment by GaHoKwan** [comment]
已修复，请更新
