### ISSUE TITLE
无法设置推送地址

### ISSUE THREAD

**Issue by jason4677** [GaHoKwan/tvpanel#7]
后台里面 app升级设置，无法设置升级推送地址、版本等信息

**Comment by shuaigebo** [comment]
你用最新的版本能登录？不提示升级失败？

**Comment by jason4677** [comment]
app 提示升级失败

**Comment by GaHoKwan** [comment]
已修复

**Comment by jason4677** [comment]
------------------ 原始邮件 ------------------
发件人: "關嘉豪[GavinK♂luo2888]"<notifications@github.com>
发送时间: 2020年2月27日(星期四) 凌晨2:36
收件人: "GaHoKwan/tvpanel"<tvpanel@noreply.github.com>;
抄送: "jason4677"<784024103@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [GaHoKwan/tvpanel] 无法设置推送地址 (#7)



Closed #7.
 
&mdash;
